# Generated by Django 4.2.11 on 2024-08-14 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_status',
            field=models.CharField(choices=[('pending', 'Awaiting Approval'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('declined', 'Declined'), ('due', 'Due For Repayment'), ('repayed', 'Repayment Complete')], default='pending', max_length=20),
        ),
    ]
